name: Build and Publish Backend Container

on:
  push:
    branches: [ main, master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
          file: ./backend/Dockerfile
      - name: Log image pushed
        run: echo "Pushed backend image to GHCR"
